// <auto-generated />
using System;
using BloodFlow.DataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodFlow.DataLayer.Migrations
{
    [DbContext(typeof(BloodFlowDbContext))]
    [Migration("20240426130932_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.BloodType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("blood_type");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("city");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.ContactType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("contact_type");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Donor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BloodTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("blood_type_id");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeId");

                    b.ToTable("donor");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int")
                        .HasColumnName("house_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("StreetId")
                        .HasColumnType("bigint")
                        .HasColumnName("street_id");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("donor_center");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorCenterContact", b =>
                {
                    b.Property<long>("DonorCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_center_id");

                    b.Property<long>("ContactTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_type_id");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_value");

                    b.HasKey("DonorCenterId", "ContactTypeId");

                    b.HasIndex("ContactTypeId");

                    b.ToTable("donor_center_contact");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorOrder", b =>
                {
                    b.Property<long>("DonorId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.HasKey("DonorId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("donor_order");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorSession", b =>
                {
                    b.Property<long>("DonorId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_id");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("DonorId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("donor_session");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BloodVolume")
                        .HasColumnType("int")
                        .HasColumnName("blood_volume");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long>("DonorCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_center_id");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("importance");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DonorCenterId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birthday");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo_link");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("person");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.PersonContact", b =>
                {
                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("peson_id");

                    b.Property<long>("ContactTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_type_id");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_value");

                    b.HasKey("PersonId", "ContactTypeId");

                    b.HasIndex("ContactTypeId");

                    b.ToTable("person_contact");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BloodTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("blood_type_id");

                    b.Property<int>("BloodVolume")
                        .HasColumnType("int")
                        .HasColumnName("blood_volume");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<long>("DonorCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_center_id");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("session");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.SessionDonorCenter", b =>
                {
                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("DonorCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("donor_center_id");

                    b.HasKey("SessionId", "DonorCenterId");

                    b.HasIndex("DonorCenterId");

                    b.ToTable("session_donor_center");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("state");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Street", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("street");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Donor", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.BloodType", "BloodType")
                        .WithMany("Donors")
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorCenter", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.Street", "Street")
                        .WithMany("DonorCenters")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorCenterContact", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.ContactType", "ContactType")
                        .WithMany("DonorCenterContacts")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodFlow.DataLayer.Entities.DonorCenter", "DonorCenter")
                        .WithMany("DonorCenterContacts")
                        .HasForeignKey("DonorCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("DonorCenter");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorOrder", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.Donor", "Donor")
                        .WithMany("DonorOrders")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodFlow.DataLayer.Entities.Order", "Order")
                        .WithMany("DonorOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorSession", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.Donor", "Donor")
                        .WithMany("DonorSessions")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodFlow.DataLayer.Entities.Session", "Session")
                        .WithMany("DonorSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Order", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.DonorCenter", "DonorCenter")
                        .WithMany("Orders")
                        .HasForeignKey("DonorCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorCenter");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.PersonContact", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.ContactType", "ContactType")
                        .WithMany("PersonContacts")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodFlow.DataLayer.Entities.Person", "Person")
                        .WithMany("PersonContacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Session", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.State", null)
                        .WithMany("Sessions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.SessionDonorCenter", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.DonorCenter", "DonorCenter")
                        .WithMany("SessionDonorCenters")
                        .HasForeignKey("DonorCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodFlow.DataLayer.Entities.Session", "Session")
                        .WithMany("SessionDonorCenters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorCenter");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Street", b =>
                {
                    b.HasOne("BloodFlow.DataLayer.Entities.City", "City")
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.BloodType", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.ContactType", b =>
                {
                    b.Navigation("DonorCenterContacts");

                    b.Navigation("PersonContacts");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Donor", b =>
                {
                    b.Navigation("DonorOrders");

                    b.Navigation("DonorSessions");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.DonorCenter", b =>
                {
                    b.Navigation("DonorCenterContacts");

                    b.Navigation("Orders");

                    b.Navigation("SessionDonorCenters");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Order", b =>
                {
                    b.Navigation("DonorOrders");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Person", b =>
                {
                    b.Navigation("PersonContacts");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Session", b =>
                {
                    b.Navigation("DonorSessions");

                    b.Navigation("SessionDonorCenters");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.State", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BloodFlow.DataLayer.Entities.Street", b =>
                {
                    b.Navigation("DonorCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
